### ISSUE TITLE
chore: specify travis build more concrete

### ISSUE THREAD

**Issue by buehler** [smartive/giuseppe#151]
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Specifying-conditions

instead of:
```yml
stages:
  - name: test
    if: tag IS blank
  - name: deploy
    if: branch = master
```
use:
```yml
stages:
  - name: test
    if: tag IS blank
  - name: deploy
    if: branch = master AND type != pull_request
```
